version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: sales-system-db-only
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: devluizfcneto
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sales_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U devluizfcneto -d sales_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
